export const APPLICATION_NATIONALITY_OPTIONS = [
  'Afghan', 'Albanian', 'Algerian', 'American', 'Argentinian', 'Armenian', 'Australian', 'Austrian',
  'Azerbaijani', 'Bahraini', 'Bangladeshi', 'Belgian', 'Bhutanese', 'Bolivian', 'Brazilian', 'British',
  'Bulgarian', 'Cambodian', 'Cameroonian', 'Canadian', 'Chilean', 'Chinese', 'Colombian', 'Costa Rican',
  'Croatian', 'Cuban', 'Czech', 'Danish', 'Dominican', 'Egyptian', 'Emirati', 'Eritrean', 'Estonian',
  'Ethiopian', 'Filipino', 'Finnish', 'French', 'Georgian', 'German', 'Ghanaian', 'Greek', 'Guatemalan',
  'Haitian', 'Hungarian', 'Icelandic', 'Indian', 'Indonesian', 'Iranian', 'Iraqi', 'Irish', 'Israeli',
  'Italian', 'Jamaican', 'Japanese', 'Jordanian', 'Kazakhstani', 'Kenyan', 'Kuwaiti', 'Kyrgyz',
  'Laotian', 'Latvian', 'Lebanese', 'Liberian', 'Libyan', 'Lithuanian', 'Macedonian', 'Malagasy',
  'Malawian', 'Malaysian', 'Maldivian', 'Malian', 'Maltese', 'Mauritanian', 'Mauritian', 'Mexican',
  'Moldovan', 'Mongolian', 'Moroccan', 'Mozambican', 'Myanmarese', 'Namibian', 'Nepalese',
  'New Zealander', 'Nigerian', 'Norwegian', 'Omani', 'Pakistani', 'Palestinian', 'Panamanian',
  'Peruvian', 'Polish', 'Portuguese', 'Qatari', 'Romanian', 'Russian', 'Rwandan', 'Saudi',
  'Senegalese', 'Serbian', 'Singaporean', 'Slovak', 'Slovenian', 'Somali', 'South African',
  'South Korean', 'South Sudanese', 'Spanish', 'Sri Lankan', 'Sudanese', 'Swedish', 'Swiss',
  'Syrian', 'Taiwanese', 'Tajik', 'Tanzanian', 'Thai', 'Togolese', 'Trinidadian', 'Tunisian',
  'Turkish', 'Turkmen', 'Ugandan', 'Ukrainian', 'Uruguayan', 'Uzbek', 'Venezuelan', 'Vietnamese',
  'Yemeni', 'Zambian', 'Zimbabwean', 'Other',
] as const;

export const APPLICATION_COUNTRY_OPTIONS = [
  'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina',
  'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
  'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina',
  'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia',
  'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros',
  'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus',
  'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
  'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji',
  'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada',
  'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland',
  'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan',
  'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
  'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
  'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico',
  'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
  'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
  'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
  'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania',
  'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines',
  'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles',
  'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
  'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
  'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga',
  'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
  'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan', 'Vanuatu',
  'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe',
] as const;

export const APPLICATION_PHONE_CODE_OPTIONS = [
  { code: '+92', label: 'Pakistan (+92)' },
  { code: '+91', label: 'India (+91)' },
  { code: '+880', label: 'Bangladesh (+880)' },
  { code: '+977', label: 'Nepal (+977)' },
  { code: '+94', label: 'Sri Lanka (+94)' },
  { code: '+93', label: 'Afghanistan (+93)' },
  { code: '+975', label: 'Bhutan (+975)' },
  { code: '+960', label: 'Maldives (+960)' },
  { code: '+971', label: 'UAE (+971)' },
  { code: '+966', label: 'Saudi Arabia (+966)' },
  { code: '+974', label: 'Qatar (+974)' },
  { code: '+968', label: 'Oman (+968)' },
  { code: '+965', label: 'Kuwait (+965)' },
  { code: '+973', label: 'Bahrain (+973)' },
  { code: '+962', label: 'Jordan (+962)' },
  { code: '+961', label: 'Lebanon (+961)' },
  { code: '+964', label: 'Iraq (+964)' },
  { code: '+972', label: 'Israel (+972)' },
  { code: '+967', label: 'Yemen (+967)' },
  { code: '+963', label: 'Syria (+963)' },
  { code: '+970', label: 'Palestine (+970)' },
  { code: '+44', label: 'UK (+44)' },
  { code: '+49', label: 'Germany (+49)' },
  { code: '+33', label: 'France (+33)' },
  { code: '+39', label: 'Italy (+39)' },
  { code: '+34', label: 'Spain (+34)' },
  { code: '+31', label: 'Netherlands (+31)' },
  { code: '+32', label: 'Belgium (+32)' },
  { code: '+43', label: 'Austria (+43)' },
  { code: '+41', label: 'Switzerland (+41)' },
  { code: '+46', label: 'Sweden (+46)' },
  { code: '+47', label: 'Norway (+47)' },
  { code: '+45', label: 'Denmark (+45)' },
  { code: '+358', label: 'Finland (+358)' },
  { code: '+48', label: 'Poland (+48)' },
  { code: '+351', label: 'Portugal (+351)' },
  { code: '+30', label: 'Greece (+30)' },
  { code: '+40', label: 'Romania (+40)' },
  { code: '+420', label: 'Czech Republic (+420)' },
  { code: '+36', label: 'Hungary (+36)' },
  { code: '+421', label: 'Slovakia (+421)' },
  { code: '+380', label: 'Ukraine (+380)' },
  { code: '+7', label: 'Russia (+7)' },
  { code: '+90', label: 'Turkey (+90)' },
  { code: '+385', label: 'Croatia (+385)' },
  { code: '+381', label: 'Serbia (+381)' },
  { code: '+386', label: 'Slovenia (+386)' },
  { code: '+387', label: 'Bosnia & Herzegovina (+387)' },
  { code: '+389', label: 'North Macedonia (+389)' },
  { code: '+382', label: 'Montenegro (+382)' },
  { code: '+355', label: 'Albania (+355)' },
  { code: '+359', label: 'Bulgaria (+359)' },
  { code: '+370', label: 'Lithuania (+370)' },
  { code: '+371', label: 'Latvia (+371)' },
  { code: '+372', label: 'Estonia (+372)' },
  { code: '+353', label: 'Ireland (+353)' },
  { code: '+352', label: 'Luxembourg (+352)' },
  { code: '+356', label: 'Malta (+356)' },
  { code: '+357', label: 'Cyprus (+357)' },
  { code: '+354', label: 'Iceland (+354)' },
  { code: '+376', label: 'Andorra (+376)' },
  { code: '+377', label: 'Monaco (+377)' },
  { code: '+423', label: 'Liechtenstein (+423)' },
  { code: '+378', label: 'San Marino (+378)' },
  { code: '+379', label: 'Vatican City (+379)' },
  { code: '+373', label: 'Moldova (+373)' },
  { code: '+375', label: 'Belarus (+375)' },
  { code: '+374', label: 'Armenia (+374)' },
  { code: '+994', label: 'Azerbaijan (+994)' },
  { code: '+995', label: 'Georgia (+995)' },
  { code: '+383', label: 'Kosovo (+383)' },
  { code: '+1', label: 'USA / Canada (+1)' },
  { code: '+52', label: 'Mexico (+52)' },
  { code: '+502', label: 'Guatemala (+502)' },
  { code: '+503', label: 'El Salvador (+503)' },
  { code: '+504', label: 'Honduras (+504)' },
  { code: '+505', label: 'Nicaragua (+505)' },
  { code: '+506', label: 'Costa Rica (+506)' },
  { code: '+507', label: 'Panama (+507)' },
  { code: '+509', label: 'Haiti (+509)' },
  { code: '+1-809', label: 'Dominican Republic (+1-809)' },
  { code: '+1-876', label: 'Jamaica (+1-876)' },
  { code: '+1-246', label: 'Barbados (+1-246)' },
  { code: '+1-868', label: 'Trinidad & Tobago (+1-868)' },
  { code: '+1-473', label: 'Grenada (+1-473)' },
  { code: '+1-758', label: 'Saint Lucia (+1-758)' },
  { code: '+1-784', label: 'St. Vincent (+1-784)' },
  { code: '+1-767', label: 'Dominica (+1-767)' },
  { code: '+1-869', label: 'Saint Kitts & Nevis (+1-869)' },
  { code: '+1-268', label: 'Antigua & Barbuda (+1-268)' },
  { code: '+53', label: 'Cuba (+53)' },
  { code: '+55', label: 'Brazil (+55)' },
  { code: '+54', label: 'Argentina (+54)' },
  { code: '+57', label: 'Colombia (+57)' },
  { code: '+56', label: 'Chile (+56)' },
  { code: '+51', label: 'Peru (+51)' },
  { code: '+58', label: 'Venezuela (+58)' },
  { code: '+593', label: 'Ecuador (+593)' },
  { code: '+591', label: 'Bolivia (+591)' },
  { code: '+595', label: 'Paraguay (+595)' },
  { code: '+598', label: 'Uruguay (+598)' },
  { code: '+592', label: 'Guyana (+592)' },
  { code: '+597', label: 'Suriname (+597)' },
  { code: '+86', label: 'China (+86)' },
  { code: '+81', label: 'Japan (+81)' },
  { code: '+82', label: 'South Korea (+82)' },
  { code: '+886', label: 'Taiwan (+886)' },
  { code: '+850', label: 'North Korea (+850)' },
  { code: '+976', label: 'Mongolia (+976)' },
  { code: '+60', label: 'Malaysia (+60)' },
  { code: '+63', label: 'Philippines (+63)' },
  { code: '+62', label: 'Indonesia (+62)' },
  { code: '+66', label: 'Thailand (+66)' },
  { code: '+84', label: 'Vietnam (+84)' },
  { code: '+65', label: 'Singapore (+65)' },
  { code: '+95', label: 'Myanmar (+95)' },
  { code: '+855', label: 'Cambodia (+855)' },
  { code: '+856', label: 'Laos (+856)' },
  { code: '+673', label: 'Brunei (+673)' },
  { code: '+670', label: 'Timor-Leste (+670)' },
  { code: '+998', label: 'Uzbekistan (+998)' },
  { code: '+993', label: 'Turkmenistan (+993)' },
  { code: '+992', label: 'Tajikistan (+992)' },
  { code: '+996', label: 'Kyrgyzstan (+996)' },
  { code: '+20', label: 'Egypt (+20)' },
  { code: '+212', label: 'Morocco (+212)' },
  { code: '+216', label: 'Tunisia (+216)' },
  { code: '+213', label: 'Algeria (+213)' },
  { code: '+218', label: 'Libya (+218)' },
  { code: '+249', label: 'Sudan (+249)' },
  { code: '+251', label: 'Ethiopia (+251)' },
  { code: '+254', label: 'Kenya (+254)' },
  { code: '+255', label: 'Tanzania (+255)' },
  { code: '+256', label: 'Uganda (+256)' },
  { code: '+250', label: 'Rwanda (+250)' },
  { code: '+257', label: 'Burundi (+257)' },
  { code: '+252', label: 'Somalia (+252)' },
  { code: '+253', label: 'Djibouti (+253)' },
  { code: '+291', label: 'Eritrea (+291)' },
  { code: '+258', label: 'Mozambique (+258)' },
  { code: '+265', label: 'Malawi (+265)' },
  { code: '+260', label: 'Zambia (+260)' },
  { code: '+263', label: 'Zimbabwe (+263)' },
  { code: '+261', label: 'Madagascar (+261)' },
  { code: '+230', label: 'Mauritius (+230)' },
  { code: '+248', label: 'Seychelles (+248)' },
  { code: '+262', label: 'Comoros (+262)' },
  { code: '+234', label: 'Nigeria (+234)' },
  { code: '+233', label: 'Ghana (+233)' },
  { code: '+221', label: 'Senegal (+221)' },
  { code: '+225', label: 'Ivory Coast (+225)' },
  { code: '+223', label: 'Mali (+223)' },
  { code: '+226', label: 'Burkina Faso (+226)' },
  { code: '+227', label: 'Niger (+227)' },
  { code: '+224', label: 'Guinea (+224)' },
  { code: '+245', label: 'Guinea-Bissau (+245)' },
  { code: '+220', label: 'Gambia (+220)' },
  { code: '+232', label: 'Sierra Leone (+232)' },
  { code: '+231', label: 'Liberia (+231)' },
  { code: '+228', label: 'Togo (+228)' },
  { code: '+229', label: 'Benin (+229)' },
  { code: '+222', label: 'Mauritania (+222)' },
  { code: '+238', label: 'Cape Verde (+238)' },
  { code: '+239', label: 'Sao Tome & Principe (+239)' },
  { code: '+237', label: 'Cameroon (+237)' },
  { code: '+236', label: 'Central African Republic (+236)' },
  { code: '+235', label: 'Chad (+235)' },
  { code: '+241', label: 'Gabon (+241)' },
  { code: '+242', label: 'Congo (Brazzaville) (+242)' },
  { code: '+243', label: 'Congo (Kinshasa) (+243)' },
  { code: '+240', label: 'Equatorial Guinea (+240)' },
  { code: '+27', label: 'South Africa (+27)' },
  { code: '+264', label: 'Namibia (+264)' },
  { code: '+267', label: 'Botswana (+267)' },
  { code: '+266', label: 'Lesotho (+266)' },
  { code: '+268', label: 'Eswatini (+268)' },
  { code: '+244', label: 'Angola (+244)' },
  { code: '+211', label: 'South Sudan (+211)' },
  { code: '+61', label: 'Australia (+61)' },
  { code: '+64', label: 'New Zealand (+64)' },
  { code: '+675', label: 'Papua New Guinea (+675)' },
  { code: '+679', label: 'Fiji (+679)' },
  { code: '+677', label: 'Solomon Islands (+677)' },
  { code: '+678', label: 'Vanuatu (+678)' },
  { code: '+676', label: 'Tonga (+676)' },
  { code: '+685', label: 'Samoa (+685)' },
  { code: '+686', label: 'Kiribati (+686)' },
  { code: '+674', label: 'Nauru (+674)' },
  { code: '+680', label: 'Palau (+680)' },
  { code: '+692', label: 'Marshall Islands (+692)' },
  { code: '+691', label: 'Micronesia (+691)' },
  { code: '+688', label: 'Tuvalu (+688)' },
] as const;